all: tp correction
	echo "done"


tp: *.tex
	pdflatex -shell-escape -jobname="tp1" tp1.tex
	pdflatex -shell-escape -jobname="tp1" tp1.tex


correction: *.tex
	pdflatex -shell-escape -jobname=tp1_correction "\def\koriG{} \input{tp1.tex}"
	pdflatex -shell-escape -jobname=tp1_correction "\def\koriG{} \input{tp1.tex}"

clean:
	rm -f tp1_correction.pdf rm tp1.pdf
	rm -f *.idx *.aux *.log *.nav *.out *.snm *.toc